# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.section .text

.byte  0x80, 0x37, 0x12, 0x40 # PI BSD Domain 1 register
.word  0x0000000F # clock rate setting
.word  0x80000400 # entry point
.word  0x00001446 # release
.word  0x3E5055B6 # checksum1
.word  0x2E92DA52 # checksum2
.word  0x00000000 # unknown
.word  0x00000000 # unknown
.ascii "MARIOKART64         " # ROM name: 20 bytes
.word  0x00000000 # unknown
.word  0x0000004E # cartridge
.ascii "KT"       # cartridge ID
.ascii "E"        # country
.byte  0x00       # version
