# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"

.section .data

glabel rsp.boot
.incbin "bin/mk64.u.0D9B70.rsp.boot.bin"
glabel rsp.boot_end
rsp.graphics:
.incbin "bin/mk64.u.0D9C40.rsp.graphics.bin"
glabel rsp.graphics_end
# Unknown region 0DAC40-0DC430 [17F0]
.incbin "bin/mk64.u.0DAC40.bin"

glabel rsp.audio
.incbin "bin/mk64.u.0DC430.rsp.audio.bin"
glabel rsp.audio_end
# Unknown region 0DD430-0F7510 [1A0E0]
.incbin "bin/mk64.u.0DD430.bin"
